services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    IchHabRecht\SocialGdpr\Hooks\ContentPostProcessHook:
        tags:
            -   name: event.listener
                identifier: 'socialgdprAfterCacheableContentIsGeneratedEventListener'
                event: TYPO3\CMS\Frontend\Event\AfterCacheableContentIsGeneratedEvent
                method: replaceSocialMediaWithEvent
